version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest

env_variables:
   GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'

handlers:
- url: /.*
  script: helloworld.app
